import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Ecom Suite",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className + " overflow-x-hidden"}>
                <main className="w-screen h-full relative bg-slate-50 ">
                    {children}
                    <Footer></Footer>
                </main>
            </body>
        </html>
    );
}
